version: 0.0.1

achievements:
  - achievement:
      name: Debugging Dynamo
      icon: https://raw.githubusercontent.com/unifyai/ivy/main/.vaunt/badges/badge_01-00.png
      description: Awarded for creating useful issues.
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: count(created_at >= "2023-12-26") >= 1

  - achievement:
      name: Pull Request Pioneer
      icon: https://raw.githubusercontent.com/unifyai/ivy/main/.vaunt/badges/badge_03-00.png
      description: Awarded for creating pull requests.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(created_at >= "2023-12-26") >= 1

  - achievement:
      name: Merging Master
      icon: https://raw.githubusercontent.com/unifyai/ivy/main/.vaunt/badges/badge_04-00.png
      description: Awarded for getting pull requests merged.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(merged = true & created_at >= "2023-12-26") >= 1

  - achievement:
      name: Merging Wizard
      icon: https://raw.githubusercontent.com/unifyai/ivy/main/.vaunt/badges/badge_05-00.png
      description: Awarded for getting priority pull requests merged.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(merged = true & labels in {'Priority PR'} & created_at >= "2023-12-26") >= 1

  - achievement:
      name: Ivy Inspectors
      icon: https://raw.githubusercontent.com/unifyai/ivy/main/.vaunt/badges/badge_06-00.png
      description: Awarded for reviewing pull requests.
      triggers:
        - trigger:
            actor: reviewer
            action: pull_request
            condition: count(created_at >= "2023-12-26" & merged = true) >= 1

  - achievement:
      name: Debugging Dynamo Bronze
      icon: https://raw.githubusercontent.com/unifyai/ivy/main/.vaunt/badges/badge_01-02.png
      description: Awarded for creating 5 useful issues.
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: count(created_at >= "2023-12-26") >= 5

  - achievement:
      name: Pull Request Pioneer Bronze
      icon: https://raw.githubusercontent.com/unifyai/ivy/main/.vaunt/badges/badge_03-02.png
      description: Awarded for creating 5 pull requests.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(created_at >= "2023-12-26") >= 5

  - achievement:
      name: Merging Master Bronze
      icon: https://raw.githubusercontent.com/unifyai/ivy/main/.vaunt/badges/badge_04-02.png
      description: Awarded for getting 5 pull requests merged.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(merged = true & created_at >= "2023-12-26") >= 5

  - achievement:
      name: Merging Wizard Bronze
      icon: https://raw.githubusercontent.com/unifyai/ivy/main/.vaunt/badges/badge_05-02.png
      description: Awarded for getting 5 priority pull requests merged.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(merged = true & labels in {'Priority PR'} & created_at >= "2023-12-26") >= 5

  - achievement:
      name: Ivy Inspectors Bronze
      icon: https://raw.githubusercontent.com/unifyai/ivy/main/.vaunt/badges/badge_06-02.png
      description: Awarded for reviewing 5 pull requests.
      triggers:
        - trigger:
            actor: reviewer
            action: pull_request
            condition: count(created_at >= "2023-12-26" & merged = true) >= 5

  - achievement:
      name: Debugging Dynamo Silver
      icon: https://raw.githubusercontent.com/unifyai/ivy/main/.vaunt/badges/badge_01-03.png
      description: Awarded for creating 15 useful issues.
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: count(created_at >= "2023-12-26") >= 15

  - achievement:
      name: Pull Request Pioneer Silver
      icon: https://raw.githubusercontent.com/unifyai/ivy/main/.vaunt/badges/badge_03-03.png
      description: Awarded for creating 15 pull requests.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(created_at >= "2023-12-26") >= 15

  - achievement:
      name: Merging Master Silver
      icon: https://raw.githubusercontent.com/unifyai/ivy/main/.vaunt/badges/badge_04-03.png
      description: Awarded for getting 15 pull requests merged.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(merged = true & created_at >= "2023-12-26") >= 15

  - achievement:
      name: Merging Wizard Silver
      icon: https://raw.githubusercontent.com/unifyai/ivy/main/.vaunt/badges/badge_05-03.png
      description: Awarded for getting 15 priority pull requests merged.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(merged = true & labels in {'Priority PR'} & created_at >= "2023-12-26") >= 15

  - achievement:
      name: Ivy Inspectors Silver
      icon: https://raw.githubusercontent.com/unifyai/ivy/main/.vaunt/badges/badge_06-03.png
      description: Awarded for reviewing 15 pull requests.
      triggers:
        - trigger:
            actor: reviewer
            action: pull_request
            condition: count(created_at >= "2023-12-26" & merged = true) >= 15

  - achievement:
      name: Debugging Dynamo Gold
      icon: https://raw.githubusercontent.com/unifyai/ivy/main/.vaunt/badges/badge_01-04.png
      description: Awarded for creating 30 useful issues.
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: count(created_at >= "2023-12-26") >= 30

  - achievement:
      name: Pull Request Pioneer Gold
      icon: https://raw.githubusercontent.com/unifyai/ivy/main/.vaunt/badges/badge_03-04.png
      description: Awarded for creating 30 pull requests.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(created_at >= "2023-12-26") >= 30

  - achievement:
      name: Merging Master Gold
      icon: https://raw.githubusercontent.com/unifyai/ivy/main/.vaunt/badges/badge_04-04.png
      description: Awarded for getting 30 pull requests merged.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(merged = true & created_at >= "2023-12-26") >= 30

  - achievement:
      name: Merging Wizard Gold
      icon: https://raw.githubusercontent.com/unifyai/ivy/main/.vaunt/badges/badge_05-04.png
      description: Awarded for getting 30 priority pull requests merged.
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: count(merged = true & labels in {'Priority PR'} & created_at >= "2023-12-26") >= 30

  - achievement:
      name: Ivy Inspectors Gold
      icon: https://raw.githubusercontent.com/unifyai/ivy/main/.vaunt/badges/badge_06-04.png
      description: Awarded for reviewing 30 pull requests.
      triggers:
        - trigger:
            actor: reviewer
            action: pull_request
            condition: count(created_at >= "2023-12-26" & merged = true) >= 30
