project:
  type: website
  output-dir: docs

website:
  sidebar:
    logo: "assets/img/ivy_logo.png"
    collapse-level: 1
    contents: 
      - auto: "*unify_existing_code/"
      - auto: "*temp_demos/"

format:
  html:
    theme: assets/css/custom.scss
