project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  sidebar:
    logo: "assets/img/ivy_logo.png"
    collapse-level: 1
    contents: 
      - auto: "*unify_existing_code/"
      - auto: "*temp_demos/"

format:
  html:
    theme: assets/css/custom.scss
    page-layout: full
    code-overflow: scroll
    jupyter: python3
    monobackgroundcolor: "#f9f9f8"
    execute:
      echo: true
      output: true
      eval: true
