project:
  type: website
  output-dir: docs
  resources:
    - "scripts/deepmind_perceiver_io.py"

website:
  title: "Tutorials and Examples - Ivy"
  favicon: "assets/img/ivy_logo_only.png"

  page-navigation: true

  navbar:
    title: false
    search: true
    pinned: true
    logo: "assets/img/ivy_logo_text.png"
    logo-href: https://unify.ai
    left:
      - text: "Github"
        href: https://github.com/unifyai/ivy
      - text: "Docs"
        href: https://unify.ai/docs/ivy
      - text: "Discord"
        href: https://discord.com/invite/sXyFF8tDtm

  sidebar:
    style: "floating"
    border: true
    collapse-level: 1
    contents:
      - quickstart.ipynb
      - section: "Learn the Basics"
        contents:
          - "learn_the_basics/01_write_ivy_code.ipynb"
          - "learn_the_basics/02_unify_code.ipynb"
          - "learn_the_basics/03_compile_code.ipynb"
          - "learn_the_basics/04_transpile_code.ipynb"
          - "learn_the_basics/05_lazy_vs_eager.ipynb"
          - "learn_the_basics/06_how_to_use_decorators.ipynb"
          - "learn_the_basics/07_transpile_any_library.ipynb"
          - "learn_the_basics/08_transpile_any_model.ipynb"
      - section: "Guides"
        contents:
          - "guides/01_transpiling_a_torch_model.ipynb"
          - "guides/03_transpiling_a_tf_model.ipynb" 
      - section: "Examples and Demos"
        contents:
          - "examples_and_demos/resnet_demo.ipynb"
          - "examples_and_demos/torch_to_jax.ipynb"
          - "examples_and_demos/mmpretrain_to_jax.ipynb"
          - "examples_and_demos/image_segmentation_with_ivy_unet.ipynb"
          - "examples_and_demos/alexnet_demo.ipynb"

format:
  html:
    toc: true
    include-after-body:
      - file: assets/generate_badges.html
    theme: assets/css/custom.scss
    page-layout: full
    code-overflow: scroll
    jupyter: python3
    monobackgroundcolor: "#ffffff"
    execute:
      echo: true
      output: true
      eval: true