name: array-api-determine-test-coverage
on:
  workflow_dispatch:
#   schedule:
#     - cron: "30 20 * * 6"

permissions:
  actions: read
jobs:
  determine_coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: [ 1, 2, 3, 4 ]
    steps:
      - name: Checkout Ivy ðŸ›Ž
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 150

      - name: Determine Test Coverage
        run: |
          pip install pydriller tqdm
          cd ivy
          python scripts/determine_tests/array_api_det_coverage.py ${{ matrix.branch }}
          cd ..
          mkdir tests
          cp ivy/tests.pbz2 tests/

      - name: Push Mapping
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: tests/
          destination-github-username: 'unifyai'
          destination-repository-name: 'Mapping'
          user-email: ivy.branch@lets-unify.ai
          commit-message: Update Array API Tests Mapping
          target-branch: main${{ matrix.branch }}
