name: pypi
on:
  workflow_call:
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout ğŸ›ï¸Binaries
      uses: actions/checkout@v2
      with:
        repository: unifyai/binaries
        path: binaries
        persist-credentials: false

    - name: Add Tag to Binaries
      run: |
        cd binaries
        git tag ${{ github.ref_name }}
        git push origin ${{ github.ref_name }}
