name: Comment-to-Checklist

on:
  issue_comment:
    types: [created]
jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, 'add_reformatting_checklist_') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Category Substring
        uses: bhowell2/github-substring-action@v1.0.0
        id: category
        with:
          value: ${{ github.event.comment.body }}
          index_of_str: "add_reformatting_checklist_"

      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.4
        with:
          template: .github/reformat_checklist.md
          vars: |
            category_name: ${{ steps.category.outputs.substring }}

      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ github.event.comment.id }}
          body: ${{ steps.template.outputs.result }}
          edit-mode: replace
