name: determine-test-coverage
on:
  workflow_dispatch:
permissions:
  actions: read
jobs:
   job_1:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy ðŸ›Ž
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 150

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm
           cd ivy
           python determine_test_coverage.py 0
           cd ..
           mkdir tests
           cp ivy/tests.pbz2 tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master

   job_2:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy ðŸ›Ž
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 150

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm
           cd ivy
           python determine_test_coverage.py 1
           cd ..
           mkdir tests
           cp ivy/tests.pbz2 tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY2 }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping_2'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master

   job_3:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy ðŸ›Ž
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 150

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm
           cd ivy
           python determine_test_coverage.py 2
           cd ..
           mkdir tests
           cp ivy/tests.pbz2 tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY3 }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping_3'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master

   job_4:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy ðŸ›Ž
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 150

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm
           cd ivy
           python determine_test_coverage.py 3
           cd ..
           mkdir tests
           cp ivy/tests.pbz2 tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY4 }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping_4'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master

   job_5:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy ðŸ›Ž
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 150

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm
           cd ivy
           python determine_test_coverage.py 4
           cd ..
           mkdir tests
           cp ivy/tests.pbz2 tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY5 }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping_5'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master

   job_6:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy ðŸ›Ž
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 150

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm
           cd ivy
           python determine_test_coverage.py 5
           cd ..
           mkdir tests
           cp ivy/tests.pbz2 tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY6 }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping_6'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master

   job_7:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy ðŸ›Ž
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 150

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm
           cd ivy
           python determine_test_coverage.py 6
           cd ..
           mkdir tests
           cp ivy/tests.pbz2 tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY7 }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping_7'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master

   job_8:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy ðŸ›Ž
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 150

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm
           cd ivy
           python determine_test_coverage.py 7
           cd ..
           mkdir tests
           cp ivy/tests.pbz2 tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY8 }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping_8'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master

   job_9:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy ðŸ›Ž
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 150

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm
           cd ivy
           python determine_test_coverage.py 8
           cd ..
           mkdir tests
           cp ivy/tests.pbz2 tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY9 }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping_9'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master

   job_10:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy ðŸ›Ž
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 150

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm
           cd ivy
           python determine_test_coverage.py 9
           cd ..
           mkdir tests
           cp ivy/tests.pbz2 tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY10 }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping_10'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master

   job_11:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy ðŸ›Ž
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 150

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm
           cd ivy
           python determine_test_coverage.py 10
           cd ..
           mkdir tests
           cp ivy/tests.pbz2 tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY11 }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping_11'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master

   job_12:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy ðŸ›Ž
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 150

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm
           cd ivy
           python determine_test_coverage.py 11
           cd ..
           mkdir tests
           cp ivy/tests.pbz2 tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY12 }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping_12'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master

   job_13:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy ðŸ›Ž
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 150

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm
           cd ivy
           python determine_test_coverage.py 12
           cd ..
           mkdir tests
           cp ivy/tests.pbz2 tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY13 }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping_13'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master

   job_14:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy ðŸ›Ž
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 150

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm
           cd ivy
           python determine_test_coverage.py 13
           cd ..
           mkdir tests
           cp ivy/tests.pbz2 tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY14 }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping_14'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master

   job_15:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy ðŸ›Ž
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 150

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm
           cd ivy
           python determine_test_coverage.py 14
           cd ..
           mkdir tests
           cp ivy/tests.pbz2 tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY15 }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping_15'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master

   job_16:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy ðŸ›Ž
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 150

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm
           cd ivy
           python determine_test_coverage.py 15
           cd ..
           mkdir tests
           cp ivy/tests.pbz2 tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY16 }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping_16'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master
