name: Build DockerfileGPU

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [labeled]
    branches: [ "master" ]

jobs:

  build:
    if: ${{ github.event.label.name == 'with CI' }}
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build DockerfileGPU
      run: docker build . --file DockerfileGPU --tag unifyai/ivy:gpu$(date +%s)
