name: Dockerfile Push

on:
  schedule:
    # run at everyday at 00:00 UTC
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - 
      name: Checkout ðŸ›Ž Ivy
      uses: actions/checkout@v3

    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Build and push Dockerfile
      run: |
        docker build . --file docker/Dockerfile --tag unifyai/ivy:latest
        docker push unifyai/ivy:latest
