name: Dockerfile Push

on:
  schedule:
    # runs everyday at 23:00 UTC
    - cron:  '0 23 * * *'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout ðŸ›Ž Ivy
      uses: actions/checkout@v3

    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Build and push Dockerfile
      run: |
        docker build . --file docker/Dockerfile --tag ivyllc/ivy:latest
        docker push ivyllc/ivy:latest
