name: docs-cleanup
on: [push]
jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false

      - name: Checkout ğŸ›ï¸Ivy Doc Builder
        uses: actions/checkout@v2
        with:
          repository: unifyai/doc-builder
          path: ivy_doc_builder
          persist-credentials: false

      - name: Check logs
        run: |
          cd ivy
          git branch
          git remote -v
          git fetch origin gh-pages --tags
          git checkout gh-pages
          echo pwd
          echo "COMMITS"
          git log -5
          echo "TAGS"
          git describe --tags $(git rev-list --tags --max-count=1)
          git rev-list --tags --max-count=1
