name: docs_new_repo
on: [push, pull_request]
jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸Ivy
        uses: actions/checkout@v3
        with:
          repository: unifyai/ivy
          path: ivy
          persist-credentials: false

      - name: Checkout ğŸ›ï¸Ivy Doc Builder
        uses: actions/checkout@v3
        with:
          repository: unifyai/doc-builder
          path: ivy_doc_builder
          persist-credentials: false

      - name: Build Docs
        run: |
          cd ivy
          rm -rf .gitignore
          bash docs/make_docs_without_docker.sh ../ivy_doc_builder
          sudo touch .nojekyll
          sudo cp .nojekyll docs/build/
          cd ..
 
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          repository-name: unifyai/ivy-docs
          folder: ivy/docs/build
          target-folder: .
          clean: false
          git-config-name: ivy-seed
          git-config-email: ivydl.team@gmail.com
