name: docs_new_repo
on: [push]
permissions: 
  contents: write
jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è Ivy Models
        uses: actions/checkout@v3
        with:
          repository: unifyai/models
          persist-credentials: false

      - name: Build Docs
        run: |
          docker run --rm -v "$(pwd)":/project unifyai/doc-builder:latest

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: docs/build
          target-folder: models
          ssh-key: ${{ secrets.SSH_GH_PAGES }}
          branch: master
          git-config-name: ivy-seed
          git-config-email: ivydl.team@gmail.com
          repository-name: unifyai/docs
          clean: false
