name: github-release
on: [push]
jobs:
  release-if-tagged-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false

      - name: Install Dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install setuptools twine wheel

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Release on Github
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: Ivy ${{ steps.get_version.outputs.VERSION }}
          tag_name: ${{ steps.get_version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
