name: Trigger lint format

on:
  pull_request:
    types: [ labeled, opened, synchronize, reopened, review_requested ]

permissions:
  contents: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    name: Check for triggers
    outputs:
      head-ref: ${{ steps.comment-branch.outputs.head_ref }}
      head-repo: ${{ steps.comment-branch.outputs.head_owner }}/${{ steps.comment-branch.outputs.head_repo }}
    steps:
      - uses: KareemMAX/pull-request-comment-branch@head-repo-owner-release
        id: comment-branch

  format-code:
    needs: trigger
    name: Trigger lint bot
    uses: unifyai/workflows/.github/workflows/lint-bot.yml@automatic-lint-pr
    secrets: inherit
    with:
      head-ref: ${{ needs.trigger.outputs.head-ref }}
      head-repo: ${{ needs.trigger.outputs.head-repo }}
      only-changed-files: true
