name: Trigger lint format

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  fix-linting:
    name: PR Lint Bot
    if: '!contains(github.event.head_commit.message, "ðŸ¤– Lint code")'
    uses: unifyai/workflows/.github/workflows/pr-lint-bot.yml@main
    secrets: inherit
