name: Trigger lint format

on:
  issue_comment:
    types: [created]

permissions:
  contents: write

jobs:
  fix-linting:
    name: PR Lint Bot
    uses: unifyai/workflows/.github/workflows/pr-lint-bot.yml@main
    secrets: inherit
