name: Ivy PR Automation
on:
  pull_request_target:
    types: [opened]
permissions:
  pull-requests: write

jobs:
  pull_request_assigners:
    name: Issue comment
    if: ${{ github.event.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Checks
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
      - name: Assigning Ivy Intern
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: |
            cd ivy/automation_tools/pr_automation
            python3 pr_action.py $PR_NUMBER "$PR_AUTHOR" 
