name: temp
on: [push, pull_request]
permissions: 
  contents: write
jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸Ivy
        uses: actions/checkout@v3
        with:
          repository: unifyai/ivy
          path: ivy
          persist-credentials: false

      - name: Checkout ðŸ›Žï¸Ivy Doc Builder
        uses: actions/checkout@v3
        with:
          repository: unifyai/doc-builder
          path: ivy_doc_builder
          persist-credentials: false
        
      - name: Checkout ðŸ›Žï¸Ivy Docs
        uses: actions/checkout@v3
        with:
          repository: unifyai/ivy-docs
          persist-credentials: false

      - name: Temp push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name ivy-seed
          git config user.email ivydl.team@gmail.com
          touch temp.txt
          echo -n "TEXT" > temp.txt
          git remote -v
          git add temp.txt
          git commit -m "First commit"
          git push --force origin master
