name: pypi
on: [push]
jobs:
  upload-if-tagged-commit:
     runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout üõéÔ∏èIvy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false

      - name: Install Dependencies
        run: |
          sudo apt-get install python3-venv
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade build
          python3 -m pip install --upgrade twine

      - name: Upload to Pypi
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        env:
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          cd ivy
          bash deploy_pypi.sh
