name: pypi-tests
on: [push]
jobs:
  run-pypi-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false

      - name: Install Dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install wheel setuptools pytest
          pip3 install -r ivy/requirements.txt
          pip3 install -r ivy/optional.txt
          pip3 install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
          pip3 install ivy-core

      - name: Run Tests
        run: |
          mv ivy/ivy_tests ivy_tests
          python3 -m pytest ivy_tests/
