name: test-core-ivy
on: [push, pull_request]
jobs:
  run-nightly-tests:
    strategy:
      matrix:
        backends :  [numpy, torch, jax, tensorflow]
        submodules: [test_creation, test_device, test_dtype, test_elementwise, test_general, test_gradients, test_linalg
                    test_manipulation, test_meta, test_nest, test_random, test_searching, test_set, test_sorting, test_statistical
                    test_utility]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"

      - name: Cache hypothesis
        uses: actions/cache@v3
        with:
          path: |
            ivy/.hypothesis
          key: ${{ runner.os }}-hypothesis

      - name: Run Activations Tests
        run: |
          cd ivy
          mkdir -p .hypothesis
          ./test_ivy.sh ${{ matrix.backends }} ${{ matrix.submodules }}
        continue-on-error: true

      - name: Create Artifacts Folder
        run: |
        cd ivy
        mkdir downloads

      - name: Add artifacts to publish
        run:
          cd downloads
          echo 'alpha' > alpha.html


      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ivy-test-artifacts
          path: ivy/downloads
