name: test-array-api-tensorflow
on: [push, pull_request, workflow_dispatch]
jobs:
  run-tensorflow-array-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏èIvy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: 'recursive'

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test-array-api-tensorflow.yml
          workflow_conclusion: success
          name: hypothesis
          path: |
            ivy/.hypothesis
            
      - name: Run TensorFlow Tests
        id: tests
        run: |
          cd ivy
          ./test_array_api.sh tensorflow
        continue-on-error: true
        
      - name: Upload hypothesis
        uses: actions/upload-artifact@v3
        with:
          name: hypothesis
          path: |
            ivy/.hypothesis
    
      - name: Check on failures
        if: steps.tests.outcome != 'success'
        run: exit 1
