name: test-array-api
on: [push, pull_request]
jobs:
  run-jax-array-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: 'recursive'

      - name: Run JAX Tests
        run: |
          cd ivy
          ./test_array_api.sh jax
