name: Update Optional Requirements
on: workflow_dispatch

jobs:
  update-optional-requirements:
    name: Update Optional Requirements
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Ivy ğŸ›
        uses: actions/checkout@v3

      - name: Run Update Script
        shell: bash
        run: |
          pip install pur
          python update_optional_requirements.py

      - name: Check if there are changes ğŸ“
        id: check
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes ğŸ“
        if: steps.check.outputs.changes == 'true'
        run: |
          git config --local user.email "ivy.branch@lets-unify.ai"
          git config --local user.name "ivy-branch"
          git add .
          git commit -m "ğŸ¤– Update Optional Requirements"
          git push
