name: Check Semantic and welcome new contributors

on:
  pull_request_target:
    types:
      - opened
  workflow_call:

permissions:
  pull-requests: write

jobs:
  welcome:
    name: Welcome
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.action == 'opened'
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |-
            Congrats on making your first Pull Request and thanks for supporting Ivy! ğŸ‰
            Join the conversation in our [Discord](https://discord.com/invite/sXyFF8tDtm).

            For every PR opened, we run unit tests and comment the results in the PR to ensure the functionality remains intact.
            Please make sure they are passing. ğŸ’ª

            If you want to check them from the action runners, you can open the `display_test_results` job. ğŸ‘€
            It contains the following two sections:
              - **Combined Test Results:** This shows the results of all the ivy tests that ran on the PR. âœ”ï¸
              - **New Failures Introduced:** This lists the tests that fail on this PR.

            Keep in mind that we will assign an engineer for this task and they will look at it based on the workload that they have, **kindly be patient ğŸ˜„**.
